import { createSlice, PayloadAction } from "@reduxjs/toolkit";

// Define the initial state
interface ModeState {
    isLight: boolean | undefined;
}

let isLightInitial;

// Check if window is defined (i.e., we're on the client side).
if (typeof window !== 'undefined') {
    isLightInitial = localStorage.getItem("mode")?.toLowerCase() == "true";
}

const initialState: ModeState = {
    isLight: isLightInitial 
};


// Define the slice
const modeSlice = createSlice({
    name: "mode",
    initialState,
    reducers: {
        setMode: (state, action: PayloadAction<boolean>) => {
        state.isLight = action.payload;
        localStorage.setItem("mode", action.payload.toString());
        },
    },
});

// Export the actions generated by createSlice
export const { setMode } = modeSlice.actions;

// Export the reducer
export default modeSlice.reducer;
