import Head from 'next/head'
import { useEffect } from 'react'
import Header from '@/components/header'
import Sidebar from '@/components/sidebar'
import Bar from '@/components/bar'
import Empty from '@/components/empty'
import BarEdit from '@/components/barEdit'
import BarEditMobile from '@/components/barEditMobile'
import Delete from '@/components/Modal/delete'
import Allbar from '@/components/Allbar'
import GoBack from '@/components/goBack'
import EditInvoice from '@/components/editInvoice'
import { LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs'
import styles from '@/styles/Main.module.css'
import CreateInvoice from '@/components/createInvoice'
import {useSelector } from 'react-redux';
import { RootState } from '@/redux/store';
export default function Home() {
    const Mode = useSelector((state:RootState) => state.mode)
    
    const {isLight} = Mode

  useEffect(() => {
    document.body.style.backgroundColor = isLight ? '#F8F8FB' : '#141625';
  }, [isLight]); // Run this effect whenever `isLight` changes.

  return (
    <>
      <Head>
        <title>Invoice App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image/logo.svg" />
      </Head>
    <LocalizationProvider dateAdapter={AdapterDayjs}>
      <Sidebar alt={true} />
      <Allbar/>
      <CreateInvoice code='EFRD' />
      <EditInvoice  />
      <Delete />
    </LocalizationProvider>
    
    </>
  )
}
